In [4]:
import numpy as np
import torch

# PyTorch Basics

## PyTorch Operations

In [5]:
n_arr = np.arange(10).reshape(2, 5)
n_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
t_arr = torch.FloatTensor(n_arr)
t_arr

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [7]:
print(t_arr.ndim)
print(t_arr.shape)

2
torch.Size([2, 5])


In [12]:
torch.from_numpy(n_arr)
# torch.tensor(n_arr)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]], dtype=torch.int32)

In [15]:
# tensor가 올라가 있는 디바이스 확인 가능
t_arr.device

device(type='cpu')

In [17]:
torch.cuda.is_available()

False

In [18]:
tensor = torch.rand(size=(3, 3, 4))
tensor

tensor([[[0.3650, 0.1612, 0.0234, 0.2243],
         [0.6144, 0.9675, 0.3989, 0.8552],
         [0.3742, 0.1511, 0.7356, 0.6841]],

        [[0.0943, 0.9228, 0.9513, 0.0889],
         [0.1429, 0.1633, 0.8017, 0.3099],
         [0.1879, 0.4927, 0.6683, 0.3731]],

        [[0.6167, 0.4373, 0.0965, 0.8511],
         [0.1309, 0.1741, 0.7311, 0.4728],
         [0.3177, 0.5520, 0.8601, 0.0828]]])

In [19]:
# shape 변화 (view 사용을 권장)
tensor.view([-1, 6])

tensor([[0.3650, 0.1612, 0.0234, 0.2243, 0.6144, 0.9675],
        [0.3989, 0.8552, 0.3742, 0.1511, 0.7356, 0.6841],
        [0.0943, 0.9228, 0.9513, 0.0889, 0.1429, 0.1633],
        [0.8017, 0.3099, 0.1879, 0.4927, 0.6683, 0.3731],
        [0.6167, 0.4373, 0.0965, 0.8511, 0.1309, 0.1741],
        [0.7311, 0.4728, 0.3177, 0.5520, 0.8601, 0.0828]])

In [20]:
tensor.reshape([-1, 6])

tensor([[0.3650, 0.1612, 0.0234, 0.2243, 0.6144, 0.9675],
        [0.3989, 0.8552, 0.3742, 0.1511, 0.7356, 0.6841],
        [0.0943, 0.9228, 0.9513, 0.0889, 0.1429, 0.1633],
        [0.8017, 0.3099, 0.1879, 0.4927, 0.6683, 0.3731],
        [0.6167, 0.4373, 0.0965, 0.8511, 0.1309, 0.1741],
        [0.7311, 0.4728, 0.3177, 0.5520, 0.8601, 0.0828]])

In [32]:
# view와 reshape의 차이

# view : 기존 텐서가 변경되면, 형태가 바뀐 텐서도 함께 변경. 동일한 메모리 사용.
a = torch.zeros(3, 1)
b = a.view(1, 3)
a.fill_(1)
print(a)
print(b)

tensor([[1.],
        [1.],
        [1.]])
tensor([[1., 1., 1.]])


In [82]:
# reshape : 동일한 메모리를 사용하지 않고, copy. 서로 영향을 받지 않음. (1.10.1에서 적용이 안 되고 있음. transpose를 넣으면 되긴 함.)
a = torch.zeros(3, 2)
b = a.reshape(6)
a[0, 0] = 9
print(a)
print(b)

tensor([[9., 0.],
        [0., 0.],
        [0., 0.]])
tensor([9., 0., 0., 0., 0., 0.])


In [37]:
# squeeze
tensor = torch.rand(size=(2, 1, 2))
print(tensor)
print(tensor.shape)

tensor([[[0.1390, 0.1468]],

        [[0.7072, 0.5035]]])
torch.Size([2, 1, 2])


In [39]:
tensor.squeeze().shape

torch.Size([2, 2])

In [40]:
# unsqueeze
tensor = torch.rand(size=(2, 2))
print(tensor)
print(tensor.shape)

tensor([[0.8666, 0.4022],
        [0.6980, 0.4611]])
torch.Size([2, 2])


In [41]:
tensor.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [42]:
tensor.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [43]:
tensor.unsqueeze(2).shape

torch.Size([2, 2, 1])

In [44]:
# 행렬 곱셈
t1 = torch.rand(size=(2, 5))
t2 = torch.rand(size=(5, 4))

In [45]:
# dot은 행렬 곱셈을 지원하지 않음
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [46]:
# 행렬 곱셈은 mm
t1.mm(t2)

tensor([[2.2574, 2.0396, 1.4718, 1.3267],
        [1.6985, 2.0950, 1.4171, 1.2463]])

In [55]:
# dot은 벡터 내적만 지원 (1D tensor)
v1 = torch.rand(3)
v2 = torch.rand(3)
v1.dot(v2)

tensor(0.2446)

In [65]:
# matmul은 브로드캐스팅 지원
a = torch.rand(5, 2, 3)
b = torch.tensor([1.0, 1.0, 1.0])
a.matmul(b)

tensor([[1.3384, 1.6688],
        [2.0176, 1.7634],
        [1.7679, 1.4628],
        [2.0150, 1.0185],
        [1.2871, 1.1112]])

In [66]:
print(a[0])
print(b)

tensor([[0.2378, 0.3182, 0.7823],
        [0.5632, 0.4147, 0.6909]])
tensor([1., 1., 1.])


In [68]:
a[0].mm(torch.unsqueeze(b, 1)).squeeze()

tensor([1.3384, 1.6688])

## AutoGrad

In [69]:
w = torch.tensor(2.0, requires_grad=True) # w = 2일 때
u = w**2
z = 10*u + 50
z.backward()

In [70]:
w.grad

tensor(40.)

In [74]:
a = torch.tensor([2., 3.], requires_grad=True) # a = [2, 3]일 때
b = torch.tensor([6., 4.], requires_grad=True) # b = [6, 4]일 때
Q = 3*a**3 - b**2
ex_grad = torch.tensor([2., 1.])
Q.backward(gradient=ex_grad)

In [75]:
a.grad

tensor([72., 81.])

In [76]:
b.grad

tensor([-24.,  -8.])