In [1]:
a = [1, 2, 3, 4]
b = [4, 3, 2, 1]
a[0] is b[-1] # 이미 값들에 대한 메모리가 할당되어 있고, 값에 맞춰 리스트에 주소를 저장. 

True

In [2]:
import numpy as np

# 리스트와 ndarray의 차이
# C의 array와 같은 메모리 구조
an = np.array(a)
bn = np.array(b)
an[0] is bn[-1]

False

In [4]:
arr = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
aa = np.array(arr)
print(aa.shape)
print(aa.dtype)

(3, 3, 3)
int32


In [8]:
print(aa.ndim)
print(aa.size)
print(aa.nbytes)

3
27
108


### reshape

In [4]:
import numpy as np

arr = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(np.array(arr).reshape(-1, 2))    # -1 : 자동으로 reshape 되는 개수 선정 
print(np.array(arr).reshape(1, -1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4 5 6 7 8]]


### flatten

In [5]:
print(np.array(arr).flatten())

[1 2 3 4 5 6 7 8]


### slicing

In [7]:
arr = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
print(arr)
print(np.array(arr)[:2, 1:3])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[2 3]
 [6 7]]


In [8]:
# 둘의 차이
print(np.array(arr)[1])
print(np.array(arr)[1:2])

[5 6 7 8]
[[5 6 7 8]]


In [10]:
print(np.array(arr)[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]]
