In [1]:
a = [1, 2, 3, 4]
b = [4, 3, 2, 1]
a[0] is b[-1] # 이미 값들에 대한 메모리가 할당되어 있고, 값에 맞춰 리스트에 주소를 저장. 

True

In [2]:
import numpy as np

# 리스트와 ndarray의 차이
# C의 array와 같은 메모리 구조
an = np.array(a)
bn = np.array(b)
an[0] is bn[-1]

False

In [4]:
arr = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
aa = np.array(arr)
print(aa.shape)
print(aa.dtype)

(3, 3, 3)
int32


In [8]:
print(aa.ndim)
print(aa.size)
print(aa.nbytes)

3
27
108


### reshape

In [4]:
import numpy as np

arr = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(np.array(arr).reshape(-1, 2))    # -1 : 자동으로 reshape 되는 개수 선정 
print(np.array(arr).reshape(1, -1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4 5 6 7 8]]


### flatten

In [5]:
print(np.array(arr).flatten())

[1 2 3 4 5 6 7 8]


### slicing

In [7]:
arr = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
print(arr)
print(np.array(arr)[:2, 1:3])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[2 3]
 [6 7]]


In [8]:
# 둘의 차이
print(np.array(arr)[1])
print(np.array(arr)[1:2])

[5 6 7 8]
[[5 6 7 8]]


In [10]:
print(np.array(arr)[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


### creation

In [1]:
import numpy as np
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
arr = np.arange(9).reshape(3, 3)
print(arr)
np.diag(arr, k=1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([1, 5])

In [4]:
np.random.uniform(0, 1, 10)

array([0.41387725, 0.40237201, 0.17772396, 0.84632325, 0.15862714,
       0.14169177, 0.28708312, 0.03601788, 0.70595163, 0.3561241 ])

### operation

In [6]:
arr3 = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]]

# axis
print(np.array(arr3).sum(axis=0))
print(np.array(arr3).sum(axis=1))
print(np.array(arr3).sum(axis=2))

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
[[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]
[[10 26 42]
 [10 26 42]
 [10 26 42]]


In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [9]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

b = b[np.newaxis, :].T
print(b)
print(np.concatenate((a, b), axis=1))

[[5]
 [6]]
[[1 2 5]
 [3 4 6]]


###  array operation

In [11]:
# broadcasting (array, scalar)
a = np.array([0, 1, 2])
a + 4

array([4, 5, 6])

In [12]:
# broadcasting (array, array)
a = np.array([[1], [2], [3], [4]])
b = np.array([0, 1, 2])
a + b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### comparison

In [14]:
a = np.arange(10)
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [16]:
print((a < 5).any())
print(np.any(a < 5))

True
True


In [17]:
print((a < 5).all())
print(np.all(a < 5))

False
False


In [18]:
b = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
a == b

array([False,  True, False, False, False, False, False, False, False,
       False])

In [19]:
np.logical_and(a > 0, a < 7)

array([False,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [20]:
np.where(a > 5, 1, 0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [21]:
np.where(a > 5)

(array([6, 7, 8, 9], dtype=int64),)

In [22]:
c = np.array([1, np.NaN, np.Inf], float)
print(np.isnan(c))
print(np.isfinite(c))

[False  True False]
[ True False False]


In [24]:
d = a + 10
print(np.argmax(d))
print(np.argmin(d))

9
0


### boolean index

In [25]:
condition = d > 16
d[condition]

array([17, 18, 19])

### fancy index

In [31]:
e = np.array([1, 2, 3, 4, 5])
i = np.array([0, 0, 3, 4, 1, 2])   # index array = e의 크기 범위를 벗어난 값은 못 가짐
print(e[i])

[1 1 4 5 2 3]


In [32]:
i2 = [0, 5]
print(e[i2])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [30]:
# take 함수와 같은 효과
e.take(i)

array([1, 1, 4, 5, 2, 3])

In [36]:
# 2D matrix
m = np.array([[1, 2], [3, 4]])
ri = np.array([0, 0, 1, 1])
ci = np.array([0, 1, 1, 1])
m[ri, ci]

array([1, 2, 4, 4])

### data i/o

In [47]:
np.savetxt('numpy io.txt', m, delimiter=',')

In [48]:
aa = np.loadtxt('./numpy io.txt')
# print(aa)

ValueError: could not convert string to float: '1.000000000000000000e+00,2.000000000000000000e+00'

In [49]:
np.save('npy_test', arr=m)

In [50]:
test = np.load(file='npy_test.npy')
print(test)

[[1 2]
 [3 4]]
