In [1]:
import numpy as np

### 벡터

In [2]:
# L1 norm
def l1_norm(x):
    x_norm = np.abs(x)
    return np.sum(x_norm)

# L2 norm = 벡터의 크기
def l2_norm(x):
    x_norm = x * x
    x_norm = np.sum(x_norm)
    return np.sqrt(x_norm)

In [27]:
# 두 벡터 사이 각도
def angle(x, y):
    v = np.inner(x, y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta

### 행렬

In [5]:
# 행렬의 곱셈
X = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
Y = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

X = np.array(X)
Y = np.array(Y)

X @ Y

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [6]:
# 행렬의 inner product
np.inner(X, Y)

array([[ 46,  28,  10],
       [118,  73,  28],
       [190, 118,  46]])

In [14]:
# 역행렬
X = np.array([[1, 2], [3, 4]])
X_inv = np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
X @ X_inv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [22]:
# n <= m
X = np.array([[1, 2, 3],
     [4, 5, 6]])
X_inv = np.linalg.pinv(X)

In [23]:
X @ X_inv

array([[1.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [24]:
X_inv @ X

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

In [26]:
[np.append(x, [1]) for x in [[1, 2, 3], [4, 5, 6]]]

[array([1, 2, 3, 1]), array([4, 5, 6, 1])]

### 경사하강법

In [28]:
import sympy as sym
from sympy.abc import x

In [29]:
# 미분
sym.diff(sym.poly(x**2 + 2*x + 3), x)

Poly(2*x + 2, x, domain='ZZ')

In [31]:
# x에 값 넣기
sym.poly(x**2 + 2*x + 3).subs(x, 3)

18

In [35]:
def f(val):
    f_ = sym.poly(x**2 + 2*x + 3)
    return f_.subs(x, val), f_

def f_g(fun, val):
    _, f_ = fun(val)
    diff = sym.diff(f_, x)
    return diff.subs(x, val), diff

def gradient_descent(fun, init_p, lr=1e-2, eps=1e-5):
    count = 0
    val = init_p
    diff, _ = f_g(fun, val)
    while np.abs(diff) > eps:
        val = val - lr * diff
        diff, _ = f_g(fun, val)
        count += 1
        
    print('f : {}, cnt: {}, val: {}'.format(fun(val)[1], count, val))

In [36]:
gradient_descent(fun=f, init_p = 1)

f : Poly(x**2 + 2*x + 3, x, domain='ZZ'), cnt: 639, val: -0.999995051285912


In [47]:
# 편미분
from sympy.abc import y

def eval(fun, val):
    val_x, val_y = val
    fun_eval = fun.subs(x, val_x).subs(y, val_y)
    return fun_eval

def f_mul(val):
    _x, _y = val
    f_ = sym.poly(x**2 + 2*y**2)
    return eval(f_, [_x, _y]), f_

def f_g(fun, val):
    _x, _y = val
    _, f_ = fun(val)
    diff_x = sym.diff(f_, x)
    diff_y = sym.diff(f_, y)
    grad_vec = np.array([eval(diff_x, [_x, _y]), eval(diff_y, [_x, _y])], dtype=float)
    return grad_vec, [diff_x, diff_y]

def gradient_descent(fun, init_p, lr=1e-2, eps=1e-5):
    count = 0
    val = init_p
    diff, _ = f_g(fun, val)
    while np.linalg.norm(diff) > eps:
        val = val - lr * diff
        diff, _ = f_g(fun, val)
        count += 1
        
    print('f : {}, cnt: {}, val: {}'.format(fun(val)[1], count, val))

In [48]:
pt = [2, 2]
gradient_descent(fun=f_mul, init_p = pt)

f : Poly(x**2 + 2*y**2, x, y, domain='ZZ'), cnt: 639, val: [4.94871409e-06 9.38313377e-12]


### 딥러닝 학습법

In [49]:
def softmax(vec):
    denumerator = np.exp(vec - np.max(vec, axis=-1, keepdims=True))
    numerator = np.sum(denumerator, axis=-1, keepdims=True)
    val = denumerator / numerator
    return val

In [50]:
v = np.array([1, 2, 0])
softmax(v)

array([0.24472847, 0.66524096, 0.09003057])